all:
	gcc manybook.c -o manybook
	gcc simpleStruct.c -o simpleStruct
	gcc structPointer.c -o structPointer
	gcc structFunction.c -o structFunction
clean:
	rm manybook
	rm simpleStruct
	rm structPointer
	rm structFunction