all:
	gcc precision.c -o precision
	gcc coordinate.c -o coordinate
	gcc increment.c -o increment
	gcc charput.c -o charput
	gcc scanf.c -o scanf
	gcc ignore.c -o ignore

clean:
	rm precision
	rm coordinate
	rm increment
	rm charput
	rm scanf
	rm ignore