all:
	g++ 1_A.c++ -o 1_A
	g++ 1_B.c++ -o 1_B
	g++ 1_C.c++ -o 1_C
	g++ 1_D.c++ -o 1_D
	g++ 1_E.c++ -o 1_E
	g++ 1_F.c++ -o 1_F
	g++ 1_G.c++ -o 1_G
	g++ 1_H.c++ -o 1_H
	g++ 1_I.c++ -o 1_I
	g++ 1_J.c++ -o 1_J
	g++ 1_K.c++ -o 1_K
	g++ 1_L.c++ -o 1_L
	g++ 1_M.c++ -o 1_M
	g++ 1_N.c++ -o 1_N
clean:
	rm 1_A
	rm 1_B
	rm 1_C
	rm 1_D
	rm 1_E
	rm 1_F
	rm 1_G
	rm 1_H
	rm 1_I
	rm 1_J
	rm 1_K
	rm 1_L
	rm 1_M
	rm 1_N