all:
	gcc octal_16.c -o octal_16
	gcc char.c -o char
	gcc limit.c -o limit
	gcc beep.c -o beep
	gcc escape.c -o escape
	gcc manydice.c diceroll.c -o manydice
	gcc testorigin.c testextern1.c -o test

clean:
	rm octal_16
	rm char
	rm limit
	rm beep
	rm escape
	rm manydice
	rm test