all: 
	gcc macros01.c -o macros01
	gcc macros02.c -o macros02
	gcc macros03.c -o macros03
	gcc macros04.c -o macros04
	gcc macros05.c -o macros05
clean: 
	rm macros01
	rm macros02
	rm macros03
	rm macros04
	rm macros05
	rm include01.c
	rm include02.c
	rm include.h